FROM node:22.18-alpine
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml tsconfig.base.json eslint.config.mjs ./
COPY apps ./apps
COPY packages ./packages
COPY database ./database
COPY scripts ./scripts
RUN pnpm install --frozen-lockfile=false
CMD ["pnpm", "db:migrate"]

